apiVersion: v1
kind: Service
metadata:
  name: {{ template "bookstack.name" . }}
  labels:
    app: {{ template "bookstack.name" . }}
    chart: {{ template "bookstack.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "bookstack.name" . }}
    release: {{ .Release.Name }}
