version: '2'
catalog:
  name: "Janitor"
  version: "v1.6.0"
  description: "Docker cleanup"
  minimum_rancher_version: v1.3.3
  maximum_rancher_version: v1.3.99
  uuid: janitor-0
  questions:
    - variable: "FREQUENCY"
      label: "Frequency"
      description: "Run the cleanup on a cycle of this many seconds"
      default: 3600
      required: true
      type: "int"
    - variable: "EXCLUDE_LABEL"
      label: "Exclude label"
      description: "Specify a Rancher host label here that will be used to determine on which hosts the container should not deploy."
      default: janitor-exclude=true
      required: true
      type: "string"
    - variable: "KEEP_IMAGES"
      label: "Keep images"
      description: "A comma separated list of images that should never be removed"
      default: "rancher/agent:v1.2.2,rancher/agent:v1.2.3,rancher/agent:v1.2.4,rancher/agent:v1.2.5,rancher/agent:v1.2.6,rancher/agent:v1.2.7,rancher/lb-service-haproxy:v0.7.15"
      required: false
      type: "string"
    - variable: "KEEP_CONTAINERS"
      label: "Keep containers"
      description: "A comma separated list of images for running containers that should never be removed"
      default: "rancher/agent:v1.2.2,rancher/agent:v1.2.3,rancher/agent:v1.2.4,rancher/agent:v1.2.5,rancher/agent:v1.2.6,rancher/agent:v1.2.7,rancher/lb-service-haproxy:v0.7.15"
      required: false
      type: "string"
