version: '2'
services:
  docker-host-stats:
    image: pitrho/docker-host-stats
    tty: true
    command: -f ${FREQUENCY} ${STATS_TO_REPORT} -k ${KEY} --procpath ${PROCPATH} --hostname ${HOSTNAME} --diskpaths ${DISKPATHS} --cadvisorurl ${CADVISORURL} --cadvisorapi ${CADVISORAPI} ${ADDITIONAL_FLAGS}
    logging:
      driver: json-file
      options:
        max-file: '7'
        max-size: 50m
    links:
      - "cadvisor:cadvisor"
    network_mode: "container:cadvisor"
    volumes:
      - /proc:${PROCPATH}:ro

  cadvisor:
    image: google/cadvisor:v0.23.2
    log_driver: json-file
    log_opt:
      max-file: '7'
      max-size: 50m
    labels:
      io.rancher.scheduler.global: "true"
      io.rancher.scheduler.affinity:host_label_ne: ${HOST_STATS_EXCLUDE_LABEL}
      io.rancher.sidekicks: docker-host-stats
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "9090:8080"
