version: '2'
services:
  r7insightops:
    image: rhoai/r7insight-docker:v1.0.0
    command: ${COMMAND_OPTIONS} ${R7INSIGHTOPS_TOKEN}
    logging:
      driver: json-file
      options:
        max-file: '7'
        max-size: 50m
    labels:
      io.rancher.scheduler.global: "true"
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label_ne: ${EXCLUDE_LABEL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
